#!/bin/sh

set -e

SWISS_LIB_DIR=/var/lib/swiss
SWISS_USER="swiss"
SWISS_GROUP="swiss"

case "${1}" in
    remove)
        deluser --quiet --system $SWISS_USER || true
        delgroup --quiet --system --only-if-empty $SWISS_GROUP || true
        ;;

    purge)
        if [ -d "$SWISS_LIB_DIR" ]; then
            rm -rf $SWISS_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
